Customization

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -90,16 +90,17 @@ jobs:
         KERNEL_ROOT="$GITHUB_WORKSPACE/$CONFIG"
         mkdir -p "$KERNEL_ROOT"
 
+        if [ "${{ inputs.include_susfs }}" == "true" ]; then
+          echo "SUSFS4KSU=https://github.com/FalconSN/GKI_KernelSU_SUSFS" >>$GITHUB_ENV;
+        fi
         cat >> $GITHUB_ENV << EOF
         DEFCONFIG=$KERNEL_ROOT/common/arch/arm64/configs/gki_defconfig
         CONFIG=$CONFIG
         KERNEL_ROOT=$KERNEL_ROOT
-        SUSFS4KSU=$GITHUB_WORKSPACE/susfs4ksu
-        KERNEL_PATCHES=$GITHUB_WORKSPACE/kernel_patches
         ANYKERNEL3=$GITHUB_WORKSPACE/AnyKernel3
         REPO=$GITHUB_WORKSPACE/git-repo/repo
         EOF
-        
+        # KERNEL_PATCHES=$GITHUB_WORKSPACE/kernel_patches        
         mkdir -p "$GITHUB_WORKSPACE/git-repo"
         curl -L https://storage.googleapis.com/git-repo-downloads/repo -o "$GITHUB_WORKSPACE/git-repo/repo"
         chmod 0755 "$GITHUB_WORKSPACE/git-repo/repo"
@@ -110,7 +111,7 @@ jobs:
         ANYKERNEL_BRANCH="gki-2.0"
         git clone https://github.com/WildKernels/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
         rm -rf AnyKernel3/.git
-        git clone https://github.com/WildKernels/kernel_patches.git
+        # git clone https://github.com/WildKernels/kernel_patches.git
 
     - name: Initialize and Sync Kernel Source
       working-directory: ${{ env.KERNEL_ROOT }}
@@ -208,9 +209,12 @@ jobs:
               curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
             fi
             ;;
+          None)
+            :;;
         esac
 
     - name: Clone & Apply SUSFS Patches for KernelSU Variants
+      if: inputs.include_susfs
       run: |
         SUSFS_BRANCH="gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}"
         git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
@@ -430,33 +434,33 @@ jobs:
             ;;
         esac
 
-    - name: Apply Performance Patches
-      if: false
-      working-directory: ${{ env.KERNEL_ROOT }}/common
-      run: |
-        MIN_VERSION="5.16"
-        cp "$KERNEL_PATCHES/common/optimized_mem_operations.patch" ./
-        patch -p1 --forward < optimized_mem_operations.patch
-        cp "$KERNEL_PATCHES/common/file_struct_8bytes_align.patch" ./
-        patch -p1 --forward < file_struct_8bytes_align.patch
-        cp "$KERNEL_PATCHES/common/reduce_cache_pressure.patch" ./
-        patch -p1 --forward < reduce_cache_pressure.patch
-        if [[ "$(printf '%s\n' "${{ inputs.kernel_version }}" "$MIN_VERSION" | sort -V | head -n1)" = "${{ inputs.kernel_version }}" ]]; then
-          cp "$KERNEL_PATCHES/common/clear_page_16bytes_align.patch" ./
-          patch -p1 --forward < clear_page_16bytes_align.patch
-        else
-          cp "$KERNEL_PATCHES/common/clear_page_16bytes_align.patch" ./
-          sed -e 's/SYM_FUNC_START_PI(clear_page)/SYM_FUNC_START_PI(__pi_clear_page)/' clear_page_16bytes_align.patch > clear_page_16bytes_align__pi.patch
-          patch -p1 -F3 --forward < clear_page_16bytes_align__pi.patch
-        fi
+    # - name: Apply Performance Patches
+    #   if: false
+    #   working-directory: ${{ env.KERNEL_ROOT }}/common
+    #   run: |
+    #     MIN_VERSION="5.16"
+    #     cp "$KERNEL_PATCHES/common/optimized_mem_operations.patch" ./
+    #     patch -p1 --forward < optimized_mem_operations.patch
+    #     cp "$KERNEL_PATCHES/common/file_struct_8bytes_align.patch" ./
+    #     patch -p1 --forward < file_struct_8bytes_align.patch
+    #     cp "$KERNEL_PATCHES/common/reduce_cache_pressure.patch" ./
+    #     patch -p1 --forward < reduce_cache_pressure.patch
+    #     if [[ "$(printf '%s\n' "${{ inputs.kernel_version }}" "$MIN_VERSION" | sort -V | head -n1)" = "${{ inputs.kernel_version }}" ]]; then
+    #       cp "$KERNEL_PATCHES/common/clear_page_16bytes_align.patch" ./
+    #       patch -p1 --forward < clear_page_16bytes_align.patch
+    #     else
+    #       cp "$KERNEL_PATCHES/common/clear_page_16bytes_align.patch" ./
+    #       sed -e 's/SYM_FUNC_START_PI(clear_page)/SYM_FUNC_START_PI(__pi_clear_page)/' clear_page_16bytes_align.patch > clear_page_16bytes_align__pi.patch
+    #       patch -p1 -F3 --forward < clear_page_16bytes_align__pi.patch
+    #     fi
 
-    - name: Add BBG
-      if: true
-      working-directory: ${{ env.KERNEL_ROOT }}
-      run: |
-        curl -LSs https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
-        echo "CONFIG_BBG=y" >> common/arch/arm64/configs/gki_defconfig
-        sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' common/security/Kconfig
+    # - name: Add BBG
+    #   if: true
+    #   working-directory: ${{ env.KERNEL_ROOT }}
+    #   run: |
+    #     curl -LSs https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash
+    #     echo "CONFIG_BBG=y" >> common/arch/arm64/configs/gki_defconfig
+    #     sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' common/security/Kconfig
         
     - name: Apply Module Check Bypass
       if: ${{ matrix.build_type == 'Bypass' || matrix.build_type == 'Hakan' }}
@@ -547,18 +551,34 @@ jobs:
         CONFIG_IP_SET_HASH_NETPORT=y
         CONFIG_IP_SET_HASH_NETIFACE=y
         CONFIG_IP_SET_LIST_SET=y
-        
+
+        # Namespace configuration
+        CONFIG_UTS_NS=y
+        CONFIG_TIME_NS=y
+        CONFIG_IPC_NS=y
+        CONFIG_USER_NS=y
+        CONFIG_USER_NS_UNPRIVILEGED=y
+        CONFIG_PID_NS=y
+        CONFIG_NET_NS=y
         EOF
 
         echo "Checking if configs were applied..."
-        if grep -q "CONFIG_KSU=y" "${{ env.DEFCONFIG }}" && grep -q "CONFIG_KSU_SUSFS=y" "${{ env.DEFCONFIG }}" && grep -q "CONFIG_KPROBES=y" "${{ env.DEFCONFIG }}"; then
-          echo "SUCCESS: KSU, SUSFS, and KPROBES configs verified in ${{ env.DEFCONFIG }}"
+        if grep -q "CONFIG_KSU=y" "{{ env.DEFCONFIG }}" && \
+          { grep -q "CONFIG_KSU_SUSFS=y" "{{ env.DEFCONFIG }}" || {{ inputs.include_susfs == false && true || false }}; }
+           ; then
+           echo "SUCCESS: KSU, SUSFS, and KPROBES configs verified in ${{ env.DEFCONFIG }}"
         else
           echo "FAILED: KSU, SUSFS, or KPROBES configs missing in ${{ env.DEFCONFIG }}"
-          # print last 50 lines to see what happened
-          tail -n 50 "${{ env.DEFCONFIG }}"
-          exit 1
+          exit 1;
         fi
+        # if grep -q "CONFIG_KSU=y" "${{ env.DEFCONFIG }}" && grep -q "CONFIG_KSU_SUSFS=y" "${{ env.DEFCONFIG }}" && grep -q "CONFIG_KPROBES=y" "${{ env.DEFCONFIG }}"; then
+        #   echo "SUCCESS: KSU, SUSFS, and KPROBES configs verified in ${{ env.DEFCONFIG }}"
+        # else
+        #   echo "FAILED: KSU, SUSFS, or KPROBES configs missing in ${{ env.DEFCONFIG }}"
+        #   # print last 50 lines to see what happened
+        #   tail -n 50 "${{ env.DEFCONFIG }}"
+        #   exit 1
+        # fi
 
         # Remove check_defconfig
         if [[ "${{ inputs.android_version }}" == "android16" && "${{ inputs.kernel_version }}" == "6.12" ]]; then
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,8 +15,8 @@ on:
       ksu_variant:
         description: "KernelSU Variant"
         type: choice
-        options: [ KSU, WKSU, Next, RKSU]
-        default: WKSU
+        options: [ KSU, None]
+        default: None
       ksu_commit:
         description: "KSU Commit (optional)"
         type: string
@@ -24,6 +24,10 @@ on:
         required: false
       build_bypass:
         description: "Build Bypass"
+        type: boolean
+        default: false
+      include_susfs:
+        description: "Include susfs"
         type: boolean
         default: false
       # Build Selection
@@ -441,59 +445,59 @@ jobs:
         done
         wait
 
-    - name: Send Telegram Notification
-      if: inputs.release_type == 'Actions'
-      run: |
-        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
-          -F message_thread_id="${{ secrets.TELEGRAM_TOPIC_ID_GKI }}" \
-          -F text="
-          🌽 *New Kernel Actions Build Finished*
-          📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
-          ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
-          [🔗 View Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
-          -F parse_mode="Markdown"
+    # - name: Send Telegram Notification
+    #   if: inputs.release_type == 'Actions'
+    #   run: |
+    #     curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+    #       -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
+    #       -F message_thread_id="${{ secrets.TELEGRAM_TOPIC_ID_GKI }}" \
+    #       -F text="
+    #       🌽 *New Kernel Actions Build Finished*
+    #       📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
+    #       ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
+    #       [🔗 View Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
+    #       -F parse_mode="Markdown"
 
-    - name: Send Telegram Notification
-      if: inputs.release_type != 'Actions' && needs.release.result == 'success'
-      run: |
-        RELEASE_TYPE_TEXT=""
-        if [ "${{ inputs.release_type }}" == "Pre-Release" ]; then
-          RELEASE_TYPE_TEXT="🧪 *Pre-Release*"
-        else
-          RELEASE_TYPE_TEXT="🚀 *Release*"
-        fi
+    # - name: Send Telegram Notification
+    #   if: inputs.release_type != 'Actions' && needs.release.result == 'success'
+    #   run: |
+    #     RELEASE_TYPE_TEXT=""
+    #     if [ "${{ inputs.release_type }}" == "Pre-Release" ]; then
+    #       RELEASE_TYPE_TEXT="🧪 *Pre-Release*"
+    #     else
+    #       RELEASE_TYPE_TEXT="🚀 *Release*"
+    #     fi
 
-        curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-          -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
-          -F message_thread_id="${{ secrets.TELEGRAM_TOPIC_ID_GKI }}" \
-          -F text="
-          🌽 *New Kernel $RELEASE_TYPE_TEXT Uploaded*  
-          📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})  
-          ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})  
-          [🔗 View GitHub Release](https://github.com/${{ github.repository }}/releases/tag/${{ env.NEW_TAG }})" \
-          -F parse_mode="Markdown"
+    #     curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+    #       -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
+    #       -F message_thread_id="${{ secrets.TELEGRAM_TOPIC_ID_GKI }}" \
+    #       -F text="
+    #       🌽 *New Kernel $RELEASE_TYPE_TEXT Uploaded*  
+    #       📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})  
+    #       ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})  
+    #       [🔗 View GitHub Release](https://github.com/${{ github.repository }}/releases/tag/${{ env.NEW_TAG }})" \
+    #       -F parse_mode="Markdown"
 
-    - name: DM Artifacts
-      if: always()
-      run: |
-        shopt -s nullglob
-        files=("$GITHUB_WORKSPACE"/*.zip)
+    # - name: DM Artifacts
+    #   if: always()
+    #   run: |
+    #     shopt -s nullglob
+    #     files=("$GITHUB_WORKSPACE"/*.zip)
 
-        if [ ${#files[@]} -eq 0 ]; then
-            echo "No ZIP files found for DM."
-            exit 0
-        fi
+    #     if [ ${#files[@]} -eq 0 ]; then
+    #         echo "No ZIP files found for DM."
+    #         exit 0
+    #     fi
 
-        if [ -z "${{ secrets.TELEGRAM_USER_ID }}" ]; then
-            echo "Error: TELEGRAM_USER_ID secret is not set."
-            exit 1
-        fi
+    #     if [ -z "${{ secrets.TELEGRAM_USER_ID }}" ]; then
+    #         echo "Error: TELEGRAM_USER_ID secret is not set."
+    #         exit 1
+    #     fi
 
-        for file in "${files[@]}"; do
-            echo "Sending $(basename "$file") to Telegram DM..."
-            curl -v -F chat_id="${{ secrets.TELEGRAM_USER_ID }}" \
-                -F document=@"$file" \
-                -F caption="📦 Build: $(basename "$file")" \
-                https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
-        done
+    #     for file in "${files[@]}"; do
+    #         echo "Sending $(basename "$file") to Telegram DM..."
+    #         curl -v -F chat_id="${{ secrets.TELEGRAM_USER_ID }}" \
+    #             -F document=@"$file" \
+    #             -F caption="📦 Build: $(basename "$file")" \
+    #             https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
+    #     done
